# Generated by Django 5.0.3 on 2024-04-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0003_autor_retrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="retrato",
            field=models.ImageField(blank=True, null=True, upload_to="retratos"),
        ),
    ]
