# Generated by Django 5.0.3 on 2025-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteca", "0004_alter_autor_retrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="excerto",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
